In [1]:
#importing libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Loading data
df=pd.read_excel(r"C:\Users\Lilian\Downloads\NovaSuite_SaaS_Raw_Dataset.xlsx", sheet_name='Raw Data', header=2)

In [3]:
df

,Customer ID,Customer Name,Region,Industry,Acquisition Channel,Sales Rep,Plan,Billing Cycle,Contract Months,Signup Date,...,Annual Discount Applied,Seats Purchased,Seats Used,Seat Utilization Pct,Overage Charges,Support Tickets,Feature Adoption Pct,NPS Score,Payment Status,Failed Payment Retry
0,CUST-23238,Company_23238,Europe,Fintech,Organic,Carol N.,pro,Annual,12,"August 23, 2024",...,20,3,2,66.7,0,4,21.5,NaN,Pending,NaN
1,CUST-96673,Company_96673,West Africa,Fintech,Partner,Carol N.,Enterprise,Monthly,1,"April 19, 2023",...,0,35,30,85.7,0,1,86.4,1.0,Paid,NaN
2,CUST-37653,Company_37653,Europe,Healthcare,Social,Grace W.,STARTER,Annual,12,"December 28, 2023",...,20,1,1,100.0,0,8,22.8,10.0,Paid,NaN
3,CUST-19961,Company_19961,MENA,Healthcare,Organic,Grace W.,Starter,Annual,12,2024-11-02,...,0,1,1,100.0,0,9,79.0,0.0,Paid,NaN
4,CUST-85341,Company_85341,APAC,Fintech,Organic,David O.,STARTER,Annual,6,09/20/2023,...,0,1,1,100.0,0,12,5.5,3.0,Paid,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1520,CUST-43466,Company_43466,East Africa,Fintech,Direct Sales,Frank A.,starter,Monthly,1,05/04/2023,...,0,1,1,100.0,0,5,71.8,7.0,Paid,NaN
1521,CUST-98184,Company_98184,West Africa,Gov,Referral,Carol N.,Starter,Monthly,12,03/06/2024,...,0,1,1,100.0,0,3,56.5,4.0,Paid,NaN
1522,CUST-68743,Company_68743,APAC,Healthcare,Referral,Brian K.,Pro,Monthly,24,2024-06-17,...,0,14,9,64.3,0,0,69.4,10.0,Paid,NaN
1523,CUST-94246,Company_94246,NORTH AMERICA,Fintech,Referral,Frank A.,Pro Plan,Annual,12,10/13/2024,...,20,18,7,38.9,0,7,31.3,2.0,Paid,NaN
1524,CUST-15209,Company_15209,Europe,Retail,Partner,David O.,Growth,Annual,6,10/15/2024,...,0,3,2,66.7,0,10,88.7,6.0,Paid,NaN

In [4]:
df.shape

(1525, 26)

In [5]:
#column names
df.columns.tolist()

['Customer ID',
 'Customer Name',
 'Region',
 'Industry',
 'Acquisition Channel',
 'Sales Rep',
 'Plan',
 'Billing Cycle',
 'Contract Months',
 'Signup Date',
 'Churn Date',
 'Last Login Date',
 'Status',
 'MRR',
 'ARR',
 'Discount Pct',
 'Annual Discount Applied',
 'Seats Purchased',
 'Seats Used',
 'Seat Utilization Pct',
 'Overage Charges',
 'Support Tickets',
 'Feature Adoption Pct',
 'NPS Score',
 'Payment Status',
 'Failed Payment Retry']

In [6]:
#dataset information -data types and missing values
df.info

<bound method DataFrame.info of      Customer ID  Customer Name         Region    Industry  \
0     CUST-23238  Company_23238         Europe     Fintech
1     CUST-96673  Company_96673    West Africa     Fintech
2     CUST-37653  Company_37653         Europe  Healthcare
3     CUST-19961  Company_19961           MENA  Healthcare
4     CUST-85341  Company_85341           APAC     Fintech
...          ...            ...            ...         ...
1520  CUST-43466  Company_43466    East Africa     Fintech
1521  CUST-98184  Company_98184    West Africa         Gov
1522  CUST-68743  Company_68743           APAC  Healthcare
1523  CUST-94246  Company_94246  NORTH AMERICA     Fintech
1524  CUST-15209  Company_15209         Europe      Retail

     Acquisition Channel Sales Rep         Plan Billing Cycle  \
0                Organic  Carol N.          pro        Annual
1                Partner  Carol N.   Enterprise       Monthly
2                 Social  Grace W.      STARTER        Annual
3                Organic  Grace W.      Starter        Annual
4                Organic  David O.      STARTER        Annual
...                  ...       ...          ...           ...
1520        Direct Sales  Frank A.      starter       Monthly
1521            Referral  Carol N.      Starter       Monthly
1522            Referral  Brian K.          Pro       Monthly
1523            Referral  Frank A.     Pro Plan        Annual
1524             Partner  David O.       Growth        Annual

      Contract Months        Signup Date  ... Annual Discount Applied  \
0                  12    August 23, 2024  ...                      20
1                   1     April 19, 2023  ...                       0
2                  12  December 28, 2023  ...                      20
3                  12         2024-11-02  ...                       0
4                   6         09/20/2023  ...                       0
...               ...                ...  ...                     ...
1520                1         05/04/2023  ...                       0
1521               12         03/06/2024  ...                       0
1522               24         2024-06-17  ...                       0
1523               12         10/13/2024  ...                      20
1524                6         10/15/2024  ...                       0

     Seats Purchased Seats Used Seat Utilization Pct  Overage Charges  \
0                  3          2                 66.7                0
1                 35         30                 85.7                0
2                  1          1                100.0                0
3                  1          1                100.0                0
4                  1          1                100.0                0
...              ...        ...                  ...              ...
1520               1          1                100.0                0
1521               1          1                100.0                0
1522              14          9                 64.3                0
1523              18          7                 38.9                0
1524               3          2                 66.7                0

      Support Tickets  Feature Adoption Pct  NPS Score  Payment Status  \
0                   4                  21.5        NaN         Pending
1                   1                  86.4        1.0            Paid
2                   8                  22.8       10.0            Paid
3                   9                  79.0        0.0            Paid
4                  12                   5.5        3.0            Paid
...               ...                   ...        ...             ...
1520                5                  71.8        7.0            Paid
1521                3                  56.5        4.0            Paid
1522                0                  69.4       10.0            Paid
1523                7                  31.3        2.0            Paid
1524               10                  88.7        6.0            Paid

      Failed Payment Retry
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
...                    ...
1520                   NaN
1521                   NaN
1522                   NaN
1523                   NaN
1524                   NaN

[1525 rows x 26 columns]>

In [7]:
#Checking for missing values
df.isnull().sum()

Customer ID                   0
Customer Name                 0
Region                        0
Industry                    117
Acquisition Channel          65
Sales Rep                   309
Plan                          0
Billing Cycle                 0
Contract Months               0
Signup Date                   0
Churn Date                 1182
Last Login Date               0
Status                        0
MRR                           0
ARR                           0
Discount Pct                  0
Annual Discount Applied       0
Seats Purchased               0
Seats Used                    0
Seat Utilization Pct          0
Overage Charges               0
Support Tickets               0
Feature Adoption Pct          0
NPS Score                   223
Payment Status                0
Failed Payment Retry       1440
dtype: int64

In [8]:
#Checking for duplicate rows
df.duplicated().sum()

np.int64(25)

In [9]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1520    False
1521    False
1522    False
1523     True
1524     True
Length: 1525, dtype: bool

In [10]:
#DATA CLEANING
#Check for duplicate rows
#Are they true duplicates?
df[df.duplicated(keep=False)]

,Customer ID,Customer Name,Region,Industry,Acquisition Channel,Sales Rep,Plan,Billing Cycle,Contract Months,Signup Date,...,Annual Discount Applied,Seats Purchased,Seats Used,Seat Utilization Pct,Overage Charges,Support Tickets,Feature Adoption Pct,NPS Score,Payment Status,Failed Payment Retry
1,CUST-96673,Company_96673,West Africa,Fintech,Partner,Carol N.,Enterprise,Monthly,1,"April 19, 2023",...,0,35,30,85.7,0,1,86.4,1.0,Paid,NaN
3,CUST-19961,Company_19961,MENA,Healthcare,Organic,Grace W.,Starter,Annual,12,2024-11-02,...,0,1,1,100.0,0,9,79.0,0.0,Paid,NaN
8,CUST-49240,Company_49240,MENA,Fintech,Direct Sales,Eve L.,Growth Plan,Monthly,6,05/02/2024,...,0,5,4,80.0,0,11,12.8,9.0,Paid,NaN
71,CUST-75612,Company_75612,East Africa,Education,Organic,Alice M.,Pro,Monthly,12,"December 12, 2023",...,0,17,14,82.4,0,9,92.2,3.0,Paid,NaN
178,CUST-45509,Company_45509,MENA,Healthcare,Partner,Alice M.,starter,Monthly,24,"October 11, 2024",...,0,1,1,100.0,0,12,28.8,2.0,Paid,NaN
190,CUST-45018,Company_45018,Europe,Retail,Social,Alice M.,Starter,Monthly,24,10/01/2024,...,0,1,1,100.0,0,9,9.9,8.0,Paid,NaN
205,CUST-63354,Company_63354,APAC,Gov,Social,Brian K.,Growth,Monthly,12,2023-04-22,...,0,2,1,50.0,0,0,67.2,2.0,Paid,NaN
222,CUST-41830,Company_41830,North America Region,Education,Organic,Grace W.,Growth Plan,Annual,12,06/30/2024,...,20,4,3,75.0,0,10,44.1,4.0,Paid,NaN
314,CUST-99192,Company_99192,West Africa,Logistics,Direct Sales,Carol N.,Growth,Annual,1,"November 22, 2023",...,0,2,1,50.0,0,6,22.6,6.0,Paid,NaN
321,CUST-45697,Company_45697,NORTH AMERICA,NGO,Direct Sales,Alice M.,Growth,Monthly,12,2023-12-22,...,0,5,1,20.0,0,6,16.7,10.0,Paid,NaN
357,CUST-45697,Company_45697,NORTH AMERICA,NGO,Direct Sales,Alice M.,Growth,Monthly,12,2023-12-22,...,0,5,1,20.0,0,6,16.7,10.0,Paid,NaN
359,CUST-45018,Company_45018,Europe,Retail,Social,Alice M.,Starter,Monthly,24,10/01/2024,...,0,1,1,100.0,0,9,9.9,8.0,Paid,NaN
372,CUST-59735,Company_59735,MENA,Healthcare,Paid Search,Brian K.,Starter Plan,Monthly,1,2024-02-07,...,0,1,1,100.0,0,9,52.4,1.0,Paid,NaN
381,CUST-69469,Company_69469,East_Africa,Gov,Organic,David O.,Growth,Annual,12,2024-05-09,...,20,2,1,50.0,0,3,49.0,4.0,Paid,NaN
438,CUST-38305,Company_38305,West Africa,Retail,Organic,Frank A.,Growth,Annual,1,2024-08-15,...,0,4,3,75.0,0,11,30.7,7.0,Paid,NaN
484,CUST-67199,Company_67199,APAC,Fintech,Social,Frank A.,Growth,Monthly,1,08/06/2023,...,0,3,2,66.7,0,9,98.5,1.0,Paid,NaN
514,CUST-91381,Company_91381,Europe,Fintech,Social,Carol N.,Growth,Annual,1,10/13/2024,...,0,4,3,75.0,0,1,20.1,2.0,Paid,NaN
515,CUST-16826,Company_16826,MENA,Retail,Direct Sales,Grace W.,starter,Monthly,12,07/23/2024,...,0,1,1,100.0,0,3,54.7,4.0,Paid,NaN
545,CUST-49240,Company_49240,MENA,Fintech,Direct Sales,Eve L.,Growth Plan,Monthly,6,05/02/2024,...,0,5,4,80.0,0,11,12.8,9.0,Paid,NaN
555,CUST-63354,Company_63354,APAC,Gov,Social,Brian K.,Growth,Monthly,12,2023-04-22,...,0,2,1,50.0,0,0,67.2,2.0,Paid,NaN
568,CUST-97900,Company_97900,MENA,Gov,Referral,Alice M.,Growth,Annual,1,"June 12, 2023",...,0,1,1,100.0,0,6,62.5,9.0,Paid,NaN
578,CUST-48890,Company_48890,East Africa,Education,Organic,Frank A.,Starter,Monthly,6,2024-04-08,...,0,1,1,100.0,0,5,7.0,8.0,Pending,NaN
593,CUST-69469,Company_69469,East_Africa,Gov,Organic,David O.,Growth,Annual,12,2024-05-09,...,20,2,1,50.0,0,3,49.0,4.0,Paid,NaN
643,CUST-22656,Company_22656,MENA,Logistics,Referral,Brian K.,Growth,Annual,12,"June 22, 2024",...,20,4,1,25.0,0,5,34.4,5.0,Paid,NaN
668,CUST-33021,Company_33021,Europe,Education,NaN,NaN,STARTER,Monthly,6,2023-02-04,...,0,1,1,100.0,0,10,34.5,0.0,Failed,Retried-Success
699,CUST-41830,Company_41830,North America Region,Education,Organic,Grace W.,Growth Plan,Annual,12,06/30/2024,...,20,4,3,75.0,0,10,44.1,4.0,Paid,NaN
701,CUST-67199,Company_67199,APAC,Fintech,Social,Frank A.,Growth,Monthly,1,08/06/2023,...,0,3,2,66.7,0,9,98.5,1.0,Paid,NaN
729,CUST-91381,Company_91381,Europe,Fintech,Social,Carol N.,Growth,Annual,1,10/13/2024,...,0,4,3,75.0,0,1,20.1,2.0,Paid,NaN
827,CUST-27781,Company_27781,NORTH AMERICA,Logistics,Social,Frank A.,Pro,Monthly,12,2024-11-19,...,0,18,11,61.1,0,10,56.3,6.0,Paid,NaN
924,CUST-52237,Company_52237,North America,Healthcare,Paid Search,Frank A.,Growth,Annual,12,2023-09-22,...,20,2,1,50.0,0,10,93.5,5.0,Paid,NaN
934,CUST-38305,Company_38305,West Africa,Retail,Organic,Frank A.,Growth,Annual,1,2024-08-15,...,0,4,3,75.0,0,11,30.7,7.0,Paid,NaN
954,CUST-52237,Company_52237,North America,Healthcare,Paid Search,Frank A.,Growth,Annual,12,2023-09-22,...,20,2,1,50.0,0,10,93.5,5.0,Paid,NaN
957,CUST-45509,Company_45509,MENA,Healthcare,Partner,Alice M.,starter,Monthly,24,"October 11, 2024",...,0,1,1,100.0,0,12,28.8,2.0,Paid,NaN
984,CUST-99166,Company_99166,APAC,Fintech,Organic,Grace W.,STARTER,Annual,1,02/25/2023,...,0,1,1,100.0,0,10,92.4,NaN,Paid,NaN
1047,CUST-15209,Company_15209,Europe,Retail,Partner,David O.,Growth,Annual,6,10/15/2024,...,0,3,2,66.7,0,10,88.7,6.0,Paid,NaN
1151,CUST-75612,Company_75612,East Africa,Education,Organic,Alice M.,Pro,Monthly,12,"December 12, 2023",...,0,17,14,82.4,0,9,92.2,3.0,Paid,NaN
1163,CUST-59735,Company_59735,MENA,Healthcare,Paid Search,Brian K.,Starter Plan,Monthly,1,2024-02-07,...,0,1,1,100.0,0,9,52.4,1.0,Paid,NaN
1181,CUST-48890,Company_48890,East Africa,Education,Organic,Frank A.,Starter,Monthly,6,2024-04-08,...,0,1,1,100.0,0,5,7.0,8.0,Pending,NaN
1205,CUST-22656,Company_22656,MENA,Logistics,Referral,Brian K.,Growth,Annual,12,"June 22, 2024",...,20,4,1,25.0,0,5,34.4,5.0,Paid,NaN
1294,CUST-94246,Company_94246,NORTH AMERICA,Fintech,Referral,Frank A.,Pro Plan,Annual,12,10/13/2024,...,20,18,7,38.9,0,7,31.3,2.0,Paid,NaN
1391,CUST-99192,Company_99192,West Africa,Logistics,Direct Sales,Carol N.,Growth,Annual,1,"November 22, 2023",...,0,2,1,50.0,0,6,22.6,6.0,Paid,NaN
1405,CUST-16826,Company_16826,MENA,Retail,Direct Sales,Grace W.,starter,Monthly,12,07/23/2024,...,0,1,1,100.0,0,3,54.7,4.0,Paid,NaN
1462,CUST-97900,Company_97900,MENA,Gov,Referral,Alice M.,Growth,Annual,1,"June 12, 2023",...,0,1,1,100.0,0,6,62.5,9.0,Paid,NaN
1491,CUST-99166,Company_99166,APAC,Fintech,Organic,Grace W.,STARTER,Annual,1,02/25/2023,...,0,1,1,100.0,0,10,92.4,NaN,Paid,NaN
1497,CUST-96673,Company_96673,West Africa,Fintech,Partner,Carol N.,Enterprise,Monthly,1,"April 19, 2023",...,0,35,30,85.7,0,1,86.4,1.0,Paid,NaN
1505,CUST-19961,Company_19961,MENA,Healthcare,Organic,Grace W.,Starter,Annual,12,2024-11-02,...,0,1,1,100.0,0,9,79.0,0.0,Paid,NaN
1511,CUST-27781,Company_27781,NORTH AMERICA,Logistics,Social,Frank A.,Pro,Monthly,12,2024-11-19,...,0,18,11,61.1,0,10,56.3,6.0,Paid,NaN
1512,CUST-33021,Company_33021,Europe,Education,NaN,NaN,STARTER,Monthly,6,2023-02-04,...,0,1,1,100.0,0,10,34.5,0.0,Failed,Retried-Success
1523,CUST-94246,Company_94246,NORTH AMERICA,Fintech,Referral,Frank A.,Pro Plan,Annual,12,10/13/2024,...,20,18,7,38.9,0,7,31.3,2.0,Paid,NaN
1524,CUST-15209,Company_15209,Europe,Retail,Partner,David O.,Growth,Annual,6,10/15/2024,...,0,3,2,66.7,0,10,88.7,6.0,Paid,NaN

In [11]:
#Removing duplicates
df = df.drop_duplicates().reset_index(drop=True)

#check if any rows are remaining after cleaning
df.duplicated().sum()

np.int64(0)

In [12]:
#Fixing MRR Column
df["MRR_Raw"] = df["MRR"]

df["MRR"] = (
    df["MRR"]
    .astype(str)
    .str.replace(r"[^0-9.]", "", regex=True)
    .astype(float)
)

In [13]:
df["MRR"]

0       179.28
1       799.00
2        23.20
3        24.65
4        29.00
         ...
1495     18.56
1496     29.00
1497     29.00
1498     29.00
1499    249.00
Name: MRR, Length: 1500, dtype: float64

In [14]:
df["Signup Date"].head()

0      August 23, 2024
1       April 19, 2023
2    December 28, 2023
3           2024-11-02
4           09/20/2023
Name: Signup Date, dtype: object

In [15]:
#Cleaning Mixed-Up Date Formats
DATE_COLS = ["Signup Date", "Last Login Date", "Churn Date"]

for col in DATE_COLS:
    df[f"{col}_Raw"] = df[col]

    df[col] = pd.to_datetime(
        df[col],
        format="mixed",
        dayfirst=False,
        errors="coerce"
    )

In [16]:
df[DATE_COLS]

     Signup Date Last Login Date Churn Date
0     2024-08-23      2024-12-10        NaT
1     2023-04-19      2024-12-27        NaT
2     2023-12-28      2024-03-01 2024-03-06
3     2024-11-02      2024-12-31        NaT
4     2023-09-20      2024-12-27        NaT
...          ...             ...        ...
1495  2024-06-21      2024-12-27        NaT
1496  2024-08-11      2024-12-24        NaT
1497  2023-05-04      2024-07-08        NaT
1498  2024-03-06      2024-12-01 2024-12-31
1499  2024-06-17      2024-12-02        NaT

[1500 rows x 3 columns]

In [17]:
#Plan names
df["Plan"].value_counts(dropna=False)

Plan
Starter            317
Growth             297
Pro                218
Enterprise         132
starter             57
Growth Plan         51
STARTER             51
PRO                 47
Starter Plan        46
GROWTH              44
growth              43
Pro Plan            41
pro                 31
 Growth             26
 Enterprise         20
enterprise          19
 Starter            19
Enterprise Plan     16
ENTERPRISE          14
 Pro                11
Name: count, dtype: int64

In [18]:
#Standardise plan names
# Clean
df["Plan"] = (
    df["Plan"]
    .str.strip()
    .str.replace(" Plan", "", regex=False)
    .str.title()
)

#Verify
df["Plan"].value_counts()

Plan
Starter       490
Growth        461
Pro           348
Enterprise    201
Name: count, dtype: int64

In [19]:
#Region names
df["Region"].value_counts(dropna=False)

Region
APAC                    235
MENA                    229
North America           195
Europe                  194
East Africa             182
West Africa             157
NORTH AMERICA            30
East_Africa              28
East Africa Region       26
North America Region     25
APAC Region              24
EUROPE                   24
North_America            23
West_Africa              23
WEST AFRICA              22
West Africa Region       22
MENA Region              22
EAST AFRICA              20
Europe Region            19
Name: count, dtype: int64

In [20]:
# Cleaning
df["Region"] = (
    df["Region"]
    .str.replace("_", " ", regex=False)
    .str.replace(" Region", "", regex=False)
    .str.strip()
    .str.title()
)

# Verifying
df["Region"].unique()

array(['Europe', 'West Africa', 'Mena', 'Apac', 'East Africa',
       'North America'], dtype=object)

In [21]:
#Checking for missing values
df.isnull().sum()

Customer ID                   0
Customer Name                 0
Region                        0
Industry                    117
Acquisition Channel          64
Sales Rep                   308
Plan                          0
Billing Cycle                 0
Contract Months               0
Signup Date                   0
Churn Date                 1159
Last Login Date               0
Status                        0
MRR                           0
ARR                           0
Discount Pct                  0
Annual Discount Applied       0
Seats Purchased               0
Seats Used                    0
Seat Utilization Pct          0
Overage Charges               0
Support Tickets               0
Feature Adoption Pct          0
NPS Score                   222
Payment Status                0
Failed Payment Retry       1416
MRR_Raw                       0
Signup Date_Raw               0
Last Login Date_Raw           0
Churn Date_Raw             1159
dtype: int64

In [22]:
#Replacing 3 categorical columns that have nulls with unknown 
categorical_cols = [
    "Industry",
    "Acquisition Channel",
    "Sales Rep"
]

for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

In [23]:
#Dealing with null sales reps
df["Sales Rep"] = df["Sales Rep"].replace("N/A", "Unknown")

In [24]:
#Flagging missing NPS
df["NPS_Missing_Flag"] = df["NPS Score"].isnull().astype(int)

In [25]:
#Failed Payment Retry
df["Failed Payment Retry"].value_counts(dropna=False)

Failed Payment Retry
NaN                1416
Not Retried          31
Retried-Failed       27
Retried-Success      26
Name: count, dtype: int64

In [26]:
#Fixing failed payment retry
#nulls mean the customer likely didn’t have a failed payment, not that data is missing
df["Failed Payment Retry"] = df["Failed Payment Retry"].fillna("No Failed Payment")

In [27]:
#Validating MRR vs ARR
#ARR should equal monthly recurring revenue × 12
df["Expected_ARR"] = df["MRR"] * 12

df["ARR_Difference"] = df["ARR"] - df["Expected_ARR"]

df[df["ARR_Difference"].abs() > 0.01]

Empty DataFrame
Columns: [Customer ID, Customer Name, Region, Industry, Acquisition Channel, Sales Rep, Plan, Billing Cycle, Contract Months, Signup Date, Churn Date, Last Login Date, Status, MRR, ARR, Discount Pct, Annual Discount Applied, Seats Purchased, Seats Used, Seat Utilization Pct, Overage Charges, Support Tickets, Feature Adoption Pct, NPS Score, Payment Status, Failed Payment Retry, MRR_Raw, Signup Date_Raw, Last Login Date_Raw, Churn Date_Raw, NPS_Missing_Flag, Expected_ARR, ARR_Difference]
Index: []

[0 rows x 33 columns]

In [28]:
#Clean validation flag
df["ARR_Valid_Flag"] = (df["ARR_Difference"].abs() <= 0.01).astype(int)

In [29]:
df["ARR_Valid_Flag"]

0       1
1       1
2       1
3       1
4       1
       ..
1495    1
1496    1
1497    1
1498    1
1499    1
Name: ARR_Valid_Flag, Length: 1500, dtype: int64

In [30]:
#Add days since last login
reference_date = df["Last Login Date"].max()

df["Days_Since_Login"] = (
    reference_date - df["Last Login Date"]
).dt.days

In [32]:
df["Days_Since_Login"]

0        21
1         4
2       305
3         0
4         4
       ...
1495      4
1496      7
1497    176
1498     30
1499     29
Name: Days_Since_Login, Length: 1500, dtype: int64

In [33]:
#Adding useful Power BI flags
df["Is_Churned"] = df["Churn Date"].notna().astype(int)

df["Low_Utilization_Flag"] = (
    df["Seat Utilization Pct"] < 50
).astype(int)

df["High_Support_Flag"] = (
    df["Support Tickets"] >= 8
).astype(int)

df["Inactive_60_Days_Flag"] = (
    df["Days_Since_Login"] > 60
).astype(int)

In [34]:
#Final quality check
df.info()

df.isnull().sum()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 39 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Customer ID              1500 non-null   object
 1   Customer Name            1500 non-null   object
 2   Region                   1500 non-null   object
 3   Industry                 1500 non-null   object
 4   Acquisition Channel      1500 non-null   object
 5   Sales Rep                1500 non-null   object
 6   Plan                     1500 non-null   object
 7   Billing Cycle            1500 non-null   object
 8   Contract Months          1500 non-null   int64
 9   Signup Date              1500 non-null   datetime64[ns]
 10  Churn Date               341 non-null    datetime64[ns]
 11  Last Login Date          1500 non-null   datetime64[ns]
 12  Status                   1500 non-null   object
 13  MRR                      1500 non-null   float64
 14  ARR                      1500 non-null   float64
 15  Discount Pct             1500 non-null   int64
 16  Annual Discount Applied  1500 non-null   int64
 17  Seats Purchased          1500 non-null   int64
 18  Seats Used               1500 non-null   int64
 19  Seat Utilization Pct     1500 non-null   float64
 20  Overage Charges          1500 non-null   int64
 21  Support Tickets          1500 non-null   int64
 22  Feature Adoption Pct     1500 non-null   float64
 23  NPS Score                1278 non-null   float64
 24  Payment Status           1500 non-null   object
 25  Failed Payment Retry     1500 non-null   object
 26  MRR_Raw                  1500 non-null   object
 27  Signup Date_Raw          1500 non-null   object
 28  Last Login Date_Raw      1500 non-null   object
 29  Churn Date_Raw           341 non-null    object
 30  NPS_Missing_Flag         1500 non-null   int64
 31  Expected_ARR             1500 non-null   float64
 32  ARR_Difference           1500 non-null   float64
 33  ARR_Valid_Flag           1500 non-null   int64
 34  Days_Since_Login         1500 non-null   int64
 35  Is_Churned               1500 non-null   int64
 36  Low_Utilization_Flag     1500 non-null   int64
 37  High_Support_Flag        1500 non-null   int64
 38  Inactive_60_Days_Flag    1500 non-null   int64
dtypes: datetime64[ns](3), float64(7), int64(14), object(15)
memory usage: 457.2+ KB

,Contract Months,Signup Date,Churn Date,Last Login Date,MRR,ARR,Discount Pct,Annual Discount Applied,Seats Purchased,Seats Used,...,NPS Score,NPS_Missing_Flag,Expected_ARR,ARR_Difference,ARR_Valid_Flag,Days_Since_Login,Is_Churned,Low_Utilization_Flag,High_Support_Flag,Inactive_60_Days_Flag
count,1500.000000,1500,341,1500,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,...,1278.000000,1500.000000,1500.000000,1.500000e+03,1500.0,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,9.315333,2023-12-25 03:22:33.600000256,2024-05-21 00:04:13.372433920,2024-10-03 05:17:45.600000,187.951993,2255.423920,5.003333,3.666667,7.113333,4.260667,...,5.086072,0.148000,2255.423920,3.960092e-15,1.0,88.779333,0.227333,0.196667,0.374000,0.340000
min,1.000000,2023-01-01 00:00:00,2023-03-18 00:00:00,2023-03-15 00:00:00,11.600000,139.200000,0.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,139.200000,-9.094947e-13,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,2023-07-06 12:00:00,2023-12-26 00:00:00,2024-09-29 00:00:00,29.000000,348.000000,0.000000,0.000000,1.000000,1.000000,...,2.000000,0.000000,348.000000,0.000000e+00,1.0,5.000000,0.000000,0.000000,0.000000,0.000000
50%,12.000000,2023-12-29 00:00:00,2024-06-10 00:00:00,2024-12-09 00:00:00,99.000000,1188.000000,0.000000,0.000000,3.000000,1.000000,...,5.000000,0.000000,1188.000000,0.000000e+00,1.0,22.000000,0.000000,0.000000,0.000000,0.000000
75%,12.000000,2024-06-12 06:00:00,2024-11-14 00:00:00,2024-12-26 00:00:00,249.000000,2988.000000,0.000000,0.000000,9.000000,4.000000,...,8.000000,0.000000,2988.000000,0.000000e+00,1.0,93.000000,0.000000,0.000000,1.000000,1.000000
max,24.000000,2024-12-01 00:00:00,2024-12-31 00:00:00,2024-12-31 00:00:00,799.000000,9588.000000,50.000000,20.000000,50.000000,46.000000,...,10.000000,1.000000,9588.000000,9.094947e-13,1.0,657.000000,1.000000,1.000000,1.000000,1.000000
std,7.463312,NaN,NaN,NaN,230.818505,2769.822058,11.495133,7.741372,10.270872,6.920741,...,3.193883,0.355218,2769.822058,1.926925e-13,0.0,135.532198,0.419249,0.397611,0.484025,0.473867

In [35]:
#Exporting clean file to Excel
df.to_excel("NovaSuite_SaaS_Cleaned.xlsx", index=False)